//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASOC.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURRENT_STATUS
    {
        public decimal ID { get; set; }
        public Nullable<decimal> ID_COMPLECT { get; set; }
        public Nullable<decimal> ID_STATUS { get; set; }
        public Nullable<System.DateTime> DATE_STATUS { get; set; }
    
        public virtual COMPONENT COMPONENT { get; set; }
        public virtual STATUS STATUS { get; set; }
    }
}
